### ISSUE TITLE
match太灵活了

### ISSUE THREAD

**Issue by fanchenio** [zh-lx/pinyin-pro#101]
比如“百度网盘”四个字，这里面只有“度”是多音字，也就是说可以是，baiduwangpan、baiduowangpan，首字母是bdwp，我输入oa两个字母的时候也能match上，很费解，虽然是有duo这个拼音，但是起码是我输入duo之后再匹配上。

**Comment by zh-lx** [comment]
感谢反馈，我看看这周内为 `match` api 增加一个控制匹配灵活的参数

**Comment by fanchenio** [comment]
@zh-lx 希望可以全拼匹配、首字母匹配，这两种，目前的match太灵敏了，我试了一下，搜出了好多无效数据，根本不搭边的。

**Comment by zh-lx** [comment]
好的

**Comment by zh-lx** [comment]
感谢反馈，已在 #106 中重写了 [match](https://pinyin-pro.cn/use/match.html) API 支持该功能，欢迎体验
