### ISSUE TITLE
package.json add exports

### ISSUE THREAD

**Issue by baboon-king** [zh-lx/pinyin-pro#102]
## 功能描述
目前这个包，没有在 package.json 中 指定 exports 的描述，在 esm 中，导入时，会获得一个错误

类似如下错误
```shell
SyntaxError: Named export 'xx' not found. The requested module 'xx' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'xx';
const { b, a } = pkg;
```
这是我在 Nuxt 中得到的错误，他默认使用 Vite
```shell
@acme/nuxt:dev:  ERROR  [worker reload] [worker init] The requested module 'file:///Users/baboon/iduo/iduo-scheme-store/node_modules/pinyin-pro/dist/index.js' does not provide an export named 'pinyin'
@acme/nuxt:dev: 
@acme/nuxt:dev:   import { pinyin } from '/Users/baboon/iduo/iduo-scheme-store/node_modules/pinyin-pro/dist/index.js';
@acme/nuxt:dev:   ^^^^^^
@acme/nuxt:dev:   SyntaxError: The requested module '/Users/baboon/iduo/iduo-scheme-store/node_modules/pinyin-pro/dist/index.js' does not provide an export named 'pinyin'
@acme/nuxt:dev:   at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
@acme/nuxt:dev:   at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
@acme/nuxt:dev: 
```

相关资料 
https://es6.ruanyifeng.com/#docs/module-loader#package-json-%E7%9A%84-exports-%E5%AD%97%E6%AE%B5
https://juejin.cn/post/7132326156329549838
https://nodejs.org/api/packages.html#exports

这个也是目前对于多格式输出的库的主流用法
这是 Vue https://github.com/vuejs/core/blob/main/packages/vue/package.json#L22-L70
当然还有一些其他库

如果你没有时间，我愿意帮助你做这件事情。

最后 感谢你维护了这个库，为众多开发者节省了时间😄

**Comment by baboon-king** [comment]
还有一个问题，我看到 node_modules/pinyin-pro/dist/index.es.js 的文件是 esm 格式的，但是他被压缩和混淆了，这对 打包器 做 tree-shaking 不是很友好

**Comment by zh-lx** [comment]
> ## 功能描述
> 目前这个包，没有在 package.json 中 指定 exports 的描述，在 esm 中，导入时，会获得一个错误
> 
> 类似如下错误
> 
> ```shell
> SyntaxError: Named export 'xx' not found. The requested module 'xx' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'xx';
> const { b, a } = pkg;
> ```
> 
> 这是我在 Nuxt 中得到的错误，他默认使用 Vite
> 
> ```shell
> @acme/nuxt:dev:  ERROR  [worker reload] [worker init] The requested module 'file:///Users/baboon/iduo/iduo-scheme-store/node_modules/pinyin-pro/dist/index.js' does not provide an export named 'pinyin'
> @acme/nuxt:dev: 
> @acme/nuxt:dev:   import { pinyin } from '/Users/baboon/iduo/iduo-scheme-store/node_modules/pinyin-pro/dist/index.js';
> @acme/nuxt:dev:   ^^^^^^
> @acme/nuxt:dev:   SyntaxError: The requested module '/Users/baboon/iduo/iduo-scheme-store/node_modules/pinyin-pro/dist/index.js' does not provide an export named 'pinyin'
> @acme/nuxt:dev:   at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
> @acme/nuxt:dev:   at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
> @acme/nuxt:dev: 
> ```
> 
> 相关资料 https://es6.ruanyifeng.com/#docs/module-loader#package-json-%E7%9A%84-exports-%E5%AD%97%E6%AE%B5 https://juejin.cn/post/7132326156329549838 https://nodejs.org/api/packages.html#exports
> 
> 这个也是目前对于多格式输出的库的主流用法 这是 Vue https://github.com/vuejs/core/blob/main/packages/vue/package.json#L22-L70 当然还有一些其他库
> 
> 如果你没有时间，我愿意帮助你做这件事情。
> 
> 最后 感谢你维护了这个库，为众多开发者节省了时间😄

很棒的建议，有时间的话欢迎 PR
