### ISSUE TITLE
打包后的 esm 产物 被压缩和混淆了，这或许对打包器做 tree-shaking 不是很友好

### ISSUE THREAD

**Issue by baboon-king** [zh-lx/pinyin-pro#104]
还有一个问题，我看到 node_modules/pinyin-pro/dist/index.es.js 的文件是 esm 格式的，但是他被压缩和混淆了，这对 打包器 做 tree-shaking 不是很友好

_Originally posted by @baboon-king in https://github.com/zh-lx/pinyin-pro/issues/102#issuecomment-1569917893_

**Comment by zh-lx** [comment]
已在 `3.15.4` 版本中解决该问题欢迎下载体验
