### ISSUE TITLE
智能的能在姓氏模式下错误

### ISSUE THREAD

**Issue by 409380713** [zh-lx/pinyin-pro#109]
## 智能的能在姓氏模式下错误，翻译成了wú zhì nài

_请输入遇到的问题..._
![image](https://github.com/zh-lx/pinyin-pro/assets/28046166/fa7e7079-a42a-4611-840c-90dcf91e1ded)

**Comment by zh-lx** [comment]
姓氏模式下会优先匹配姓氏的拼音，`能(nài)` 也是一个姓氏，所以在 surname 模式下会优先使用 `nài` 这个读音。

**Comment by 409380713** [comment]
好的 感谢回复
