### ISSUE TITLE
Typescript 编译报错

### ISSUE THREAD

**Issue by danielsss** [zh-lx/pinyin-pro#111]
## bug 描述
> rm -rf ./dist/ && tsc --build tsconfig.json

node_modules/pinyin-pro/types/core/polyphonic/index.d.ts:1:34 - error TS2307: Cannot find module '@/common/type' or its corresponding type declarations.

1 import { SingleWordResult } from '@/common/type';
                                   ~~~~~~~~~~~~~~~


Found 1 error.


## pinyin-pro 版本号

3.15.2

## 环境版本号

node v16.15.1

npm 8.11.0

ts-node v10.9.1


## 引入方式

commonjs


## 本地暂时解决方案

complierOptions 添加下面两条中任意一条即可

* "paths": { "@/*": ["./node_modules/pinyin-pro/types/*"] } 
* "skipLibCheck": true

**Comment by zh-lx** [comment]
感谢反馈，我看一下哈

**Comment by zh-lx** [comment]
已在 `3.15.3` 版本中解决该问题，欢迎下载体验
