### ISSUE TITLE
汉字“的”拼音转换错误

### ISSUE THREAD

**Issue by try-to-fly** [zh-lx/pinyin-pro#112]
## Bug 描述

当我尝试将中文字符串 "杭州将成为亚洲瞩目的舞台" 转换为拼音时，字符"的"的拼音输出错误。该字符应转换为 "de"，而实际输出为 "dì"。

## 你预期的样子是？

预期结果应为："háng zhōu jiāng chéng wéi yà zhōu zhǔ mù de wǔ tái"

## pinyin-pro 版本号

pinyin-pro 3.15.2

## 引入方式
import { pinyin } from "pinyin-pro";

## 最小成本的复现步骤

请告诉我们，如何最快的复现该 bug。

- 步骤一：引入pinyin-pro库。
- 步骤二：使用以下代码转换字符串 "杭州将成为亚洲瞩目的舞台" 为拼音：
  ```javascript
  const result = pinyin('杭州将成为亚洲瞩目的舞台');
  console.log(result);
```

**Comment by zh-lx** [comment]
感谢反馈，目前纯 js 转拼音无法做到 `100%` 的转换准确率，在这个 case 会优先匹配词库中的 `目的: 'mù dì'` 这个词，目前对于你这种情况只能通过使用 `customPinyin` api 自己来兼容下：

```js
customPinyin({
  瞩目的: 'zhǔ mù de'
})

const result = pinyin('杭州将成为亚洲瞩目的舞台'); // "háng zhōu jiāng chéng wéi yà zhōu zhǔ mù de wǔ tái"
```

**Comment by try-to-fly** [comment]
好的，多谢
