### ISSUE TITLE
能否增加拼音格式转换功能，如： "han4 yu3 pin1 yin1"  --> "hàn yǔ pīn yīn"

### ISSUE THREAD

**Issue by lbb1811** [zh-lx/pinyin-pro#114]
## 功能描述

拼音格式转换
如： `han4 yu3 pin1 yin1`  --> `hàn yǔ pīn yīn`

**Comment by zh-lx** [comment]
好的，我记录一下这个需求，近期比较忙，预计 7 月底之前能够支持

**Comment by halfong** [comment]
有同样的需求，
例如让用户 用这种格式输入拼音  han4 yu3 pin1 yin1 --> hàn yǔ pīn yīn

似乎也没有其它的更方便的输入拼音的方法。

**Comment by zh-lx** [comment]
了解场景，感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月12日 18:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zh-lx/pinyin-pro] 能否增加拼音格式转换功能，如： "han4 yu3 pin1 yin1"  --> "hàn yǔ pīn yīn" (Issue #114) |

有同样的需求，
例如让用户 用这种格式输入拼音 han4 yu3 pin1 yin1 --> hàn yǔ pīn yīn

似乎也没有其它的更方便的输入拼音的方法。

**Comment by zh-lx** [comment]
@lbb1811 @halfong 已在 `3.17.0` 版本中新增 `convert` api 支持此功能，欢迎安装体验，https://pinyin-pro.cn/use/convert.html
