### ISSUE TITLE
采用字符串结果时，希望能支持分割符配置

### ISSUE THREAD

**Issue by wujiaran** [zh-lx/pinyin-pro#115]
## 采用字符串结果时，希望能支持分割符配置

即：
```js
const result = pinyin('这是simple汉语拼音', {
    pattern: 'first',
    toneType: 'none',
    nonZh: 'removed',

    // 分割符（期望增加的配置项）
    // 默认为空格，可以设置为空字符串
    // 请忽略我的取名，这只是一个示意变量名。
    separator: '',
});
// 目前输出："z s h y p y"
// 期望输出："zshypy"
```

因为需要支持用户使用首字母（或全拼）进行筛选，
而用户的输入一般是不带空格的，
所以使用不带空格的首字母或者全拼字符串，匹配会方便很多。
这样我可以使用 indexOf 进行搜索：
```
// 假设用户输入 "汉语拼音" 首字母进行搜索
"zshypy".indexOf("hypy") !== -1         // true
"z s h y p y".indexOf("hypy") !== -1    // false
```

我翻了一下历史的 issue，最后建议都是使用 array join 来解决。
尽管是可以再转一层解决，但是这个库这么高的性能，输出后我再转一下，总觉得有些可惜。
如果输出的时候就可以不带空格就好了！

🤔我没有读过源码，不知道增加这个分割符配置是否方便。
如果改动较大，您暂时不考虑这个功能，我自己项目里再封装一下，也是不影响使用的。
这个项目对我的帮助已经很大了，非常感谢！

**Comment by zh-lx** [comment]
感谢反馈，其实目前源码中字符串输出就是在数组输出的基础上手动调用了一下 join 方法，因为感觉用户通过 array 输出然后 join 一下并不麻烦，所以一直推荐了用户使用 join。不过现在看起来对于支持自定义分割符的用户还蛮多的，所以我决定支持以下这个功能，修改不麻烦，预计今晚就可以。

另外对于你说的用户筛选的这个功能，感觉 [match api](http://pinyin-pro.cn/use/match.html) 很符合你的场景，也可以看看使用 match api 会不会更加方便一些。

**Comment by zh-lx** [comment]
已在 `3.16.0` 版本中支持该功能，欢迎安装体验
```js
pinyin('汉语拼音', { separator: '-' }); // 'hàn-yǔ-pīn-yīn'
```
