### ISSUE TITLE
'苹果'转换的不正确

### ISSUE THREAD

**Issue by chenyihao2621023** [zh-lx/pinyin-pro#117]
## bug 描述

'苹果'转换成了'pinguo'
## 你预期的样子是？
'pingguo'
_请输入内容……_

## pinyin-pro 版本号

_请输入内容……_

## 引入方式

_浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by zh-lx** [comment]
感谢反馈，已在 `3.16.1` 版本中修复，请安装新版本体验
