### ISSUE TITLE
音调未能正确注音的问题

### ISSUE THREAD

**Issue by vanchKong** [zh-lx/pinyin-pro#118]
## bug 描述

音调 > yin tiao

## 你预期的样子是？

音调 > yin diao

## pinyin-pro 版本号

3.16.0

## 引入方式

esmodule(浏览器 import 引入)

## 最小成本的复现步骤

html('音 调')

**Comment by zh-lx** [comment]
感谢反馈，`音 调` 两个字如果中间空格隔开，是无法作为词汇进行多音词联想的，去掉空格可以正确识别

**Comment by vanchKong** [comment]
> 感谢反馈，`音 调` 两个字如果中间空格隔开，是无法作为词汇进行多音词联想的，去掉空格可以正确识别

基于此解决方案，应当在 `html()` 中同样增加 `separator` 选项，以防止此类问题的发生，同时需要考虑到原文本身就带有空格的情况。
这样好不好更好一些。

**Comment by zh-lx** [comment]
> `separator`

`separator` 的主要作用是用于指定输出结果的分隔符，而不是识别输入语句的分隔符。因为正常情况下连续文本是不会有空格的，空格大概率是开发者的一些格式处理，包内部兼容这些情况的成本太高但收益情况不普遍，所以需要开发者自行处理保证输入文本的正确性
