### ISSUE TITLE
增加对阿拉伯数字读音的支持

### ISSUE THREAD

**Issue by sdarpeng** [zh-lx/pinyin-pro#125]
## 功能描述

customPinyin({
	0: "ling",
	1: "yi",
	2: "er",
	3: "san",
	4: "si",
	5: "wu",
	6: "liu",
	7: "qi",
	8: "ba",
	9: "jiu",
	10: "shi",
})
const result = pinyin('123安徽庄严的序幕',{toneType: "none", pattern:"initial",v:true,separator: '-'});

console.log(result);

## 提炼几个功能点

- 功能 1
- 功能 2
- 功能 3

**Comment by zh-lx** [comment]
阿拉伯数字本身不属于汉字，而且涉及到多位数的发音无法判断，不会在默认字库中支持，如果有需要还是建议在 `customPinyin` 中自定义
