### ISSUE TITLE
关于以中性声调显示拼音的问题 Question about Displaying Pinyin with Neutral Tone

### ISSUE THREAD

**Issue by vitorjaguat** [zh-lx/pinyin-pro#126]
这个工具非常有用，非常感谢您对社区的贡献。我想知道是否有办法以最后一个音调是中性的方式来显示诸如“爷爷”，“奶奶”，“兔子”等词语的拼音。

目前，这些词语的结果显示为“yéyé”，“nǎinǎi”和“tùzǐ”，但我想获得“yéye”，“nǎinai”和“tùzi”。

如果这个问题看起来太琐碎，我很抱歉。再次感谢您。

This tool is very helpful, thank you very much for your contribution to the community. I would like to know if there is any way to display the pinyin of words like '爷爷', '奶奶', '兔子', etc., with the last tone being neutral.

Currently, the results for these words appear as 'yéyé,' 'nǎinǎi,' and 'tùzǐ,' but I would like to obtain 'yéye,' 'nǎinai,' and 'tùzi.'

I'm sorry if this question seems too trivial. Thank you once again.

**Comment by zh-lx** [comment]
感谢反馈，现在没有太好的方法去判断这种中性词的发音，不过对于“爷爷”，“奶奶”，“兔子”这种常见的中性词我会在语料库中增加这些词汇以提高识别的准确率

**Comment by vitorjaguat** [comment]
非常感谢您的回复。这是我添加到customPinyin函数的单词列表，如果您想查询的话：

    妈妈: 'mā ma',
    妹妹: 'mèi mei',
    奶奶: 'nǎi nai',
    爷爷: 'yé ye',
    爸爸: 'bà ba',
    叔叔: 'shū shu',
    耳朵: 'ěr duo',
    嘴巴: 'zuǐ ba',
    哥哥: 'gē ge',
    姐姐: 'jiě jie',
    肚子: 'dù zi'

此外，还有大多数以“子”结尾的词汇，如脖子，儿子，狮子，茄子等等。

**Comment by zh-lx** [comment]
已在 `3.16.6` 版本中补全词语，欢迎安装体验
