### ISSUE TITLE
type = all 时希望可以返回多个toneType格式 pinyin。

### ISSUE THREAD

**Issue by CodingPoorCat** [zh-lx/pinyin-pro#130]
场景需求如下：
对于多音字：“大”，前端这边需要渲染 ”dài“，后端需要“dai4”这种格式。目前没有什么办法可以很好聚合多种toneType

**Comment by zh-lx** [comment]
可以将 `type: 'all'` 和 `toneType: 'num'` 组合使用，看是否满足需求

**Comment by CodingPoorCat** [comment]
界面上是需要 toneTpye:"symbol",
![image](https://github.com/zh-lx/pinyin-pro/assets/13484062/f983119f-0ae5-4db1-9143-2e67a87ab110)
但是数据给到后端是需要 toneTpye:"number"这种形式的（da4,dai4）。所以希望 能够有类似支持

const result = pinyin('大夫', { type: 'all', toneType: ['num','symbol'] });
result  ==  {
    "origin": "大",
     "symbol":"dài", // 作为音调符号带在拼音字母上
    "pinyin": "dai4", // 作为数字跟在拼音后
    "initial": "d",
    "final": "ai4",
    "first": "d",
    "finalHead": "",
    "finalBody": "a",
    "finalTail": "i4",
    "num": 4,
    "isZh": true
}

**Comment by zh-lx** [comment]
感谢反馈，目前在 `type: 'all'` 中增加此功能可能会使 api 变得比较繁重。我在 `3.17.0` 版本中新增了 [`convert api`](https://pinyin-pro.cn/use/convert.html) 可以将带数字音调和带符号拼音互相转换，你看看是否可以将 `type: 'all'` 获取的结果通过 map 使用  convert api 在自己包装一下满足需求呢

```js
const result = pinyin('大夫', { type: 'all', toneType: ['num','symbol'] }).map(item => { ...item, pinyinWithNumber: convert(item.pinyin, { format: 'symbolToNum' }) });

```

**Comment by CodingPoorCat** [comment]
可以可以，感谢！这效率太高了！！！
