### ISSUE TITLE
做的一个项目用到了分词的功能（非拼音）

### ISSUE THREAD

**Issue by wintsa123** [zh-lx/pinyin-pro#131]
想问一下pinyin pro的分词是怎么实现的，分词进行标注，避免错误的多音字。
刚好一个项目用到了分词的功能

**Comment by zh-lx** [comment]
首先分词肯定要有一套词库，然后我基于词库初始化实现了一个 [AC自动机](https://oi-wiki.org/string/ac-automaton/)，从性能上讲 AC自动机应该是相对简单且高效的多词匹配算法，如果觉得实现有难度的话，就从头对词库的词遍历匹配也行，只不过效率和准确率相对低一点
