### ISSUE TITLE
一些词语中的轻声字，拼音处理的可能不对

### ISSUE THREAD

**Issue by NMTuan** [zh-lx/pinyin-pro#133]
## bug 描述

老师给了一套拼读组词，我嫌字太小，想重新排版打印，在使用pinyin-pro处理拼音的时候，发现有些词语中轻声字的拼音不对跟老师发的版本不同，由于是打印材料并非教科书正规内容，我不确定是否完全正确，可能也会出现偏差，望作者酌情处理。

## 你预期的样子是？

（左边是老师给的，右边是pinyin-pro生成的）

pí pa（琵琶）=== "pí pá"
mó gu（蘑菇）=== "mó gū"
hú lu（葫芦）=== "hú lú"
hú li（狐狸）=== "hú lí"
jú zi（桔子）=== "jú zǐ"
hé zi（盒子）=== "hé zǐ"
zhuō zi（桌子）=== "zhuō zǐ"
zhú zi（竹子）=== "zhú zǐ"
shī fu（师傅）=== "shī fù"
yī fu（衣服） === "yī fú"
wà zi（袜子）=== "wà zǐ"
bēi zi（杯子）=== "bēi zǐ"
cì wei（刺猬）=== "cì wèi"
mài zi（麦子） === "mài zǐ"
duì wu（队伍）=== "duì wǔ"
zhī liao（知了）=== "zhī le"     * 多音字
yú er（鱼儿）=== "yú ér"
hún tun（馄饨）=== "hún tún"
dēng long（灯笼）==="dēng lóng"
zhuāng jia（庄稼）=== "zhuāng jiā"
cōng ming（聪明）=== "cōng míng"

## pinyin-pro 版本号

当前线上 https://pinyin-pro.cn/run/run.html 

## 引入方式

线上测试地址

## 最小成本的复现步骤
-

**Comment by NMTuan** [comment]
我在“百度汉字”中查了上面的词语，除了下面这三个，其它的跟老师给的一样。

琵琶，多音字： https://hanyu.baidu.com/s?wd=%E7%90%B5%E7%90%B6&ptype=zici
知了 [ zhī liǎo ]  https://hanyu.baidu.com/s?wd=%E7%9F%A5%E4%BA%86&from=zici
聪明 多音字：https://hanyu.baidu.com/s?wd=%E8%81%AA%E6%98%8E&from=zici

**Comment by zh-lx** [comment]
已在 `3.18.0` 版本修正了上述词语，感谢反馈
