### ISSUE TITLE
IE语法报错

### ISSUE THREAD

**Issue by xingyongchao** [zh-lx/pinyin-pro#134]
你好， 我在IE11中使用此插件，因为语法没有编译，所以报语法错误，我在webpack配置了babel编译， 但是preset-env的module设置commonjs就会报错。请问如何解决

**Comment by zh-lx** [comment]
是在打包时报错吗还是运行时报错，目前项目有使用一些 es6+ 的语法，可能在 ie 中不支持，需要根据具体的错误引入对应的 polyfill 解决

**Comment by zh-lx** [comment]
暂不支持 IE 中使用，需要自行添加 polyfill 兼容
