### ISSUE TITLE
关于拼音大小写的问题

### ISSUE THREAD

**Issue by pry666** [zh-lx/pinyin-pro#137]
## 能否大小写都能识别

我想问一下，在match匹配的时候，空格是默认不参与的，那么字母大小写是不是都算对还是必须要严格小写字母才行

**Comment by zh-lx** [comment]
感谢反馈。现在的逻辑是必须要严格小写字母才行，考虑了下大小写都可以更合理一下，这周我会优化下这部分逻辑

**Comment by zh-lx** [comment]
已在 `3.18.0` 版本中支持大小写不敏感，欢迎安装体验
