### ISSUE TITLE
vue-cli-service build 编译报错

### ISSUE THREAD

**Issue by Yoyojelly** [zh-lx/pinyin-pro#140]
## bug 描述

![image](https://github.com/zh-lx/pinyin-pro/assets/43062138/197559a6-0c06-488e-9308-98f84649ca61)

## pinyin-pro 版本号

目前所有版本都报错

## 引入方式

npm i

## 最小成本的复现步骤

- vue-cli-service build

**Comment by zh-lx** [comment]
目前使用的是多少版本呢？升级到 `3.18.1` 版本试试

**Comment by Yoyojelly** [comment]
3.18.1确实可以了
