### ISSUE TITLE
部分轻读拼音标记错误

### ISSUE THREAD

**Issue by hellohejinyu** [zh-lx/pinyin-pro#154]
## bug 描述

<img width="1320" alt="image" src="https://github.com/zh-lx/pinyin-pro/assets/8766034/e3ce4948-9024-4456-bec6-99d070f80abc">

## 你预期的样子是？

在汉语拼音中，当两个相同的字连续出现时，第二个字通常会轻读，即声调变得轻柔，不强调。

## pinyin-pro 版本号

_请输入内容……_

## 引入方式

_浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by zh-lx** [comment]
这个感觉有点哄小孩子的语气才第二个字发了轻声😂，标准普通话中感觉应该发原声
<img width="661" alt="image" src="https://github.com/zh-lx/pinyin-pro/assets/73059627/c7344e03-f0d7-44fe-939f-0b61b180557b">

**Comment by hellohejinyu** [comment]
> 这个感觉有点哄小孩子的语气才第二个字发了轻声😂，标准普通话中感觉应该发原声 <img alt="image" width="661" src="https://private-user-images.githubusercontent.com/73059627/296915344-c7344e03-f0d7-44fe-939f-0b61b180557b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzMyNzIsIm5iZiI6MTcwNTM3Mjk3MiwicGF0aCI6Ii83MzA1OTYyNy8yOTY5MTUzNDQtYzczNDRlMDMtZjBkNy00NGZlLTkzOWYtMGI2MWIxODA1NTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAyNDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYTU0ODY5NmIxNDU2NjAyY2MzZjIxOTFiYWE1MjU3Mjg2NTNhNTAzNzA5NGQwY2RkZDczNTBlNzQ4MGJmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3TkVweDq9PSYvi_diYLVcTPiSVukWTWpr3WMTFp1qKA">

<img width="537" alt="image" src="https://github.com/zh-lx/pinyin-pro/assets/8766034/2de42259-6a5c-4ef3-bdf3-7b7864eee289">

我在《普通话水平测试专用教材》找到了相关说明。而且前面的那张图来自于小学一年级语文课本。课本应该是严肃性比较高的，出错的可能性不大。

**Comment by cvpv** [comment]
涉及非技术问题，这个应该问下语言学教授

**Comment by zh-lx** [comment]
> > 这个感觉有点哄小孩子的语气才第二个字发了轻声😂，标准普通话中感觉应该发原声 <img alt="image" width="661" src="https://private-user-images.githubusercontent.com/73059627/296915344-c7344e03-f0d7-44fe-939f-0b61b180557b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzMyNzIsIm5iZiI6MTcwNTM3Mjk3MiwicGF0aCI6Ii83MzA1OTYyNy8yOTY5MTUzNDQtYzczNDRlMDMtZjBkNy00NGZlLTkzOWYtMGI2MWIxODA1NTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDAyNDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYTU0ODY5NmIxNDU2NjAyY2MzZjIxOTFiYWE1MjU3Mjg2NTNhNTAzNzA5NGQwY2RkZDczNTBlNzQ4MGJmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3TkVweDq9PSYvi_diYLVcTPiSVukWTWpr3WMTFp1qKA">
> 
> <img alt="image" width="537" src="https://private-user-images.githubusercontent.com/8766034/296917933-2de42259-6a5c-4ef3-bdf3-7b7864eee289.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODg4NzYsIm5iZiI6MTcwNTM4ODU3NiwicGF0aCI6Ii84NzY2MDM0LzI5NjkxNzkzMy0yZGU0MjI1OS02YTVjLTRlZjMtYmRmMy03Yjc4NjRlZWUyODkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMDcwMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Y1NGJhMmRmZTJlZGViYTM0YzFlYWJhMDc5ZDczNWM3NjJhOGExNjg4Y2ZjMDc4MjY3ODM4N2FmNTQ1ZDA3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iIsiddLaEsmHOhGjsOVxZwRk38nzk_AlNlaq2V6EQPU">
> 我在《普通话水平测试专用教材》找到了相关说明。而且前面的那张图来自于小学一年级语文课本。课本应该是严肃性比较高的，出错的可能性不大。

好的，感谢补充，关于此部分我后续对轻声词会专门整理一个词包进行使用

**Comment by zh-lx** [comment]
汇总至 #246 中统一管理，关闭此 issue
