### ISSUE TITLE
拼音转换不正确

### ISSUE THREAD

**Issue by zlj130137** [zh-lx/pinyin-pro#155]
## bug 描述
开户行这三个字进行转换时，转换不正确，如下：
![image](https://github.com/zh-lx/pinyin-pro/assets/26791251/3b191a4d-a1b7-4c7c-ad0f-08b7785dc435)

## 你预期的样子是？
正确应该是这样的：
![image](https://github.com/zh-lx/pinyin-pro/assets/26791251/9380105d-dbd0-432f-a4ef-aa42fb87b624)

## pinyin-pro 版本号

3.19.2

## 引入方式

_浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_

## 最小成本的复现步骤

https://play.fe-dev.cn/?entry=index.html&activeFile=main.ts&openConsole=true#eNpVUr1u1EAQfpVhGyfS2YYOHXYkdASJihSJBNI2G+9wXrR/eOcunE6WKCmgokMICWp6CsLjcKTjFdi1zZGrvPv9+Zuxt0xZia+Lloxmc1bdefR0cf787BQScMJtlZ6ghV3WnKHlLGIAVYtCDqd4NkgCmlZ0ASmKLs4f5/c5g/KAb4l8jq9Wah0lz/KLh/nCGS9IXWqM4sZZQpvsT05rlMuEHQZYYTDSa4VX3nV04LlSktpa4lo1mA+XGSirSAmdh0ZorO8Vd28nkiKNJwsn8UyLDXZVOSLDbOV+uOrSyc0/j1RrUDK+TXgf11CVEZgMe1kVmk55Atr4VNY4uUrjTRHKpOaQFaURyhYUsgejf3SlbZfD2tmMTYr4SSbXFryyG2WhhxedM5CN19x3LsVwG9cRCDoMK01QT+qj7Nf1m93b7zdf3mWzmGEiqbzGOVC3QuiP91ansdBueZTd/Py2e//1948Pu8+f/lx/jLYx8zi2GrvkRvjiZXA2ttumCfhEBM7mMCAJ+18wwZylXyDMyxKDKUJb3qaTpee2Z/1fE5biMw==

**Comment by zh-lx** [comment]
已在 `3.19.3` 版本中修复，fixed on [434cf51cd](434cf51cd7c7f2a50365bfbe142c70ca93bc2344)
