### ISSUE TITLE
当 toneType: 'num' 时部分小写英文字母转换出错

### ISSUE THREAD

**Issue by vvipteam** [zh-lx/pinyin-pro#156]
## bug 描述

当 toneType: 'num' 时，text中若包含部分小写字母，会导致转换出现多余字符
具体表现为 a, e, i, n, o, u 这几个字母转换后会出现多余的 0
示例: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
转为: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ a0bcde0fghi0jklmn0o0pqrstu0vwxyz'

若同时应用 nonZh: 'consecutive' 选项，
则每个空格后的英文单词词尾都会出现 undefined
示例: 'How are you? '
转为: 'How areundefined you?undefined undefined'

## 你预期的样子是？

示例: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'
转为: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'

示例: 'How are you? '
转为: 'How are you? '

## pinyin-pro 版本号

3.19.3

## 引入方式

node
const pinyin = require('pinyin-pro').pinyin

## 最小成本的复现步骤

text: 包含小写字母 a, e, i, n, o, u 的字符串 (不论是否包含中文均可)

options: { toneType: 'num' } 以及
options: { toneType: 'num', nonZh: 'concecutive' }

**Comment by zh-lx** [comment]
感谢反馈，近期我会修复一下

**Comment by zh-lx** [comment]
感谢反馈，已在 `3.19.4` 版本中修复了该问题

**Comment by vvipteam** [comment]
> 感谢反馈，已在 `3.19.4` 版本中修复了该问题

感谢大佬如此及时的修复，赞！
