### ISSUE TITLE
非中文字符在pattern不为pinyin时输出为空字符串

### ISSUE THREAD

**Issue by minamichika** [zh-lx/pinyin-pro#158]
## bug 描述

在pattern不为pinyin时非中文字符输出一定为空字符串，并且这个空字符串不受nonZh等对于非中文字符的配置方式影响；
```
pinyin('汉语拼音very1', {
 pattern: "first",
    toneType: "none",
}) // 转换结果为h y p y

pinyin('汉语拼音very1', {
 pattern: "pinyin", // 或者默认type均可
    toneType: "none",
}) // 输出为han yu pin yin v e r y 1
```

## 你预期的样子是？

如pinyin('汉语拼音very1', {
                         pattern: "first",
                            toneType: "none",
                        })
输出应当为h y p y v e r y 1。
这个行为在3.19.3之前的老版本上应该是这样的？
因为今天我们是在无锁状态编译新包时发现的行为不一致，如果这是一个改动，希望文档能够明确补充提出。
可能是受到3.19.4为解决#156对middleware.ts修改影响默认输出空字符串导致？

## pinyin-pro 版本号

3.19.4

## 引入方式

_浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_

## 最小成本的复现步骤

直接使用在线示例输出pinyin('汉语拼音very1', {
                         pattern: "first",
                            toneType: "none",
                            type: "array"
                        })即可

**Comment by zh-lx** [comment]
感谢反馈，是在 `3.19.4` 中引起的 bug，已在 `3.19.5` 版本中修复，请升级新版本使用

**Comment by minamichika** [comment]
> 感谢反馈，是在 `3.19.4` 中引起的 bug，已在 `3.19.5` 版本中修复，请升级新版本使用

好的，已复测通过，谢谢
