### ISSUE TITLE
[语流音变]支持变调字的注音

### ISSUE THREAD

**Issue by yisibl** [zh-lx/pinyin-pro#167]
## 功能描述

[变调](https://zh.wikipedia.org/wiki/%E8%AE%8A%E8%AA%BF)又称为连读变调、连接变调，即是将[声调](https://zh.wikipedia.org/wiki/%E8%81%B2%E8%AA%BF)变化之方法使用于字词音节并合上的处理。

另有百度百科：https://baike.baidu.com/item/%E9%9F%B3%E5%8F%98/5667225

汉字常见的变调主要是「一」字和「不」字，这需要 pinyin-pro 具备识别上下文声调的功能，通过字典很难补全。具体规则详见：

- [“一”及“不”的变调](https://zh.wiktionary.org/wiki/Appendix:%E2%80%9C%E4%B8%80%E2%80%9D%E5%8F%8A%E2%80%9C%E4%B8%8D%E2%80%9D%E7%9A%84%E5%8F%98%E8%B0%83)

## 为什么这很重要？

变调虽然不属于多音字，但这是汉语基础中的基础，人教版一年级语文《秋天》中很好的表述了这一特点。支持变调将有助于教学和小朋友们的学习。

[部编版一年级知识点“一”字的变调](https://k.sina.cn/article_7070901775_1a575660f00100pxhq.html)

![秋天](https://github.com/zh-lx/pinyin-pro/assets/2784308/75c5d9e3-2edc-4536-97dd-54e981320e45)

### 当前结果

版本：3.19.6

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/8a6222a8-a0d0-4f10-b1b2-d3988f3ada78)

**Comment by yisibl** [comment]
补充材料：

- [《汉语拼音正词法基本规则》](http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75607.html)（国家标准） GB/T 16159-2012
![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/c71a32f4-de85-4686-b336-7a2a5c9a1198)
- 在书写拼音时，是否该书写变调？https://www.zhihu.com/question/45993357/answer/100434091


根据以上规则补充变调：

黄澄澄[huáng dēng dēng]

**Comment by yisibl** [comment]
建议为有变调的字增加一个新的字段用以标识。

**Comment by yisibl** [comment]
根据[《汉语拼音正词法基本规则》](http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/201001/t20100115_75607.html)

6.5.2：

> “一”、“不”一般标原调，不标变调。例如：
yī jià（一架） yī tiān（一天）
yī tóu（一头） yī wǎn(一碗)
bù qù（不去） bù duì（不对）
bùzhìyú（不至于）

> 在语言教学等方面，可根据需要按变调标写。例如：
yī tiān（一天）可标为yì tiān，bù duì（不对）可标为bú duì。

建议增加一个选项默认不开启。

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/d344bc72-8cee-4d02-8483-e64f5bc84020)

**Comment by yisibl** [comment]
## 「一」字的变调

我初步总结了一下「一」字的变调规则，欢迎指正。

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/7f230aa5-de8d-4645-b877-48d5a6275264)

比较麻烦的是，**同一个词在不同的语境下，有时候需要变调**，有时候则不变，例如：

- 这位士兵是来自一(yī)排。一(yì)排士兵站的整整齐齐。
- 厂里刚到了一(yì)台新机床。我爸每天都看中央一台(yī)的新闻联播。
- 他似乎看到了一线(yí)生机。他每天在一线(yī)非常忙。

**Comment by zh-lx** [comment]
汇总至 #246 中统一管理，关闭此 issue
