### ISSUE TITLE
「䖯、㵘」等生僻字无法生成拼音

### ISSUE THREAD

**Issue by yisibl** [zh-lx/pinyin-pro#169]
## bug 描述

输入：䶮䖯㵘燚焱渁淼，龖龘

「䶮䖯㵘」，无法生成拼音。

-「䖯」：https://www.zdic.net/hant/%E4%96%AF

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/f43926ab-7f74-4db7-8792-27c03d1f2d97)

## 你预期的样子是？

输出正确的拼音。

我不确定现在是如何判断中文区间的，但需要增加生僻字的 Unicode 区间。

### 需要支持 GB18030-2022 国标

GB18030-2022 是新版的汉字编码字符集国家标准，是全文强制性标准，市场上销售的产品必须符合。详见：全国标准信息公共服务平台 https://std.samr.gov.cn/search/std?q=GB18030-2022

### 相关参考

- [阿里巴巴普惠体 3.0](https://www.alibabafonts.com/#/font)
-  [阿里巴巴普惠体3.0来了，常用生僻字全显示](https://www.sohu.com/a/682097205_121124366)
- 思源宋体
![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/1bf54ca4-d2af-4444-bfa6-99c972f45e98)

## pinyin-pro 版本号

3.19.6

## 引入方式

浏览器 script 引入 

## 最小成本的复现步骤

```js
import { pinyin } from 'pinyin-pro';
const result = pinyin('䖯');
console.log('转换结果：', result)
```

**Comment by yisibl** [comment]
这个 issue 先不要关闭吧，所有的 GB18030-2022 国标中的汉字，字典中没有的可以不输出拼音，但我期望 `isZh` 选项都是 true。

**Comment by zh-lx** [comment]
在 #208 新增了 `inZhRange` 判断是否为中文范畴
