### ISSUE TITLE
「了」的一些词拼音不对

### ISSUE THREAD

**Issue by yisibl** [zh-lx/pinyin-pro#174]
## bug 描述

```
了不相涉 了无 了无生机
了无惧色 事了了吗 了了
了帐 了局 知了 花事了
他年婚嫁了，终老此江头
公了还是私了 已了
```

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/d8f67123-5618-44ad-8aec-8f12b5d6aa9c)

## 你预期的样子是？

类似的多音字，我们有办法通过脚本批量增加到字典吗？不然人工添加短期内始终很难完善。

这里应该都是读 `liǎo`。

关于知了，不应该轻声，参考：九年义务教育六年制小学教科书语文第二册：基础训练 6，[来源](https://blog.sina.com.cn/s/blog_166b8b8400102yycj.html)

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/d3c88a8d-b705-4fc2-8fef-0d4939b8b111)
![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/7675007b-67b8-4228-b792-fcf785f6c860)

## pinyin-pro 版本号

3.19.6

## 引入方式

浏览器 script 引入

**Comment by zh-lx** [comment]
知了 这个轻声同样是来源于一本小学读音上😂感觉从发音来看轻声更合理一些

**Comment by zh-lx** [comment]
上面的除 `他年婚假了` 和 `已了` 外其他的补充了下，这两个词场景频率太低，感觉放到基础库里不太合适，如果有需要的话最好自己维护一份数据用 customPinyin 补充

**Comment by yisibl** [comment]
「已了」还算蛮常见的吧，比如：心愿已了。

**Comment by langlanglofa** [comment]
句子中的多音字，你们是怎么处理的，就一个词典匹配，还是有通过模型预测？ @zh-lx   例如：“行行出状元，干一行爱一行，一行白鹭上青天，一行莅临指导”

**Comment by yisibl** [comment]
> 句子中的多音字，你们是怎么处理的，就一个词典匹配，还是有通过模型预测？ @zh-lx 例如：“行行出状元，干一行爱一行，一行白鹭上青天，一行莅临指导”

是通过字典的方式的。

我在这里支持了你的例子：https://github.com/zh-lx/pinyin-pro/pull/200

**Comment by yisibl** [comment]
「一行莅临指导」这里的 一行有歧义，暂时不太好解决。

**Comment by zh-lx** [comment]
汇总至 #246 中统一管理，关闭此 issue
