### ISSUE TITLE
[语流音变]轻声的智能识别

### ISSUE THREAD

**Issue by yisibl** [zh-lx/pinyin-pro#177]
## 功能描述

有没有根据一定的规则自动识别轻声？

### 版本 3.19.6

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/739e37ee-53e5-449f-9be3-07fc2fcce930)

### 《汉语拼音正词法基本规则》

![image](https://github.com/zh-lx/pinyin-pro/assets/2784308/b869fa3a-64c0-4cf4-9a96-38b1af3f7abf)

短期看，我们可以通过 OCR 识别出该规则中的拼音（或者找到[准确的文字版](https://www.htu.edu.cn/yw/2018/1008/c14029a129573/page.htm)），然后写成测试用例做一下结果比对。

**Comment by yisibl** [comment]
一些基本的轻声示例：

## 叠词 AABB 或 ABAB 形式，末尾轻声

如：看看星星、研究研究、合计合计。

## 用在名词、代词后面表示方位的语素或词有时读轻声

如：桌子**上**、屋**里**、山**上**、树**下**、地底**下**。你从这**边**往那**边**走。
以及一楼图片中的词语。

## 量词“个”常读轻声

如：一个、几个、十个

**Comment by yisibl** [comment]
> 微叹着互答着地说：“唉，天可真凉了——”（这了字念得很高，拖得很长。）—— 故都的秋，郁达夫

 「这了字」这里「了」不能轻声。

**Comment by zh-lx** [comment]
汇总至 #246 中统一管理，关闭此 issue
