### ISSUE TITLE
支持基本的语流音变

### ISSUE THREAD

**Issue by yisibl** [zh-lx/pinyin-pro#182]
## 功能描述

描述：TODO

普通话中的语流音变主要包含以下几个部分

### 变调（连读变调）Tone changes (also called Tone sandhi)

https://github.com/zh-lx/pinyin-pro/issues/167

- 「一」和 「不」字变调 Tone changes for "一"  and Tone changes for "不" 
这两个字在[中古汉语](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8F%A4%E6%BC%A2%E8%AA%9E)中属于[入声](https://zh.wikipedia.org/wiki/%E5%85%A5%E8%81%B2)字。在[中古汉语演变至官话的过程](https://zh.wikipedia.org/wiki/%E4%BB%8E%E4%B8%AD%E5%8F%A4%E6%B1%89%E8%AF%AD%E5%88%B0%E5%AE%98%E8%AF%9D%E7%9A%84%E8%AF%AD%E9%9F%B3%E6%BC%94%E5%8F%98)中，入声逐渐消失，几乎所有入声字被分派至平声、上声或去声（是为“入派三声”），因为这两个字比较常用，所以入声成分以变调的形式残留下来。

  - 「一」字变调规则详见：https://github.com/zh-lx/pinyin-pro/issues/167#issuecomment-2002484255
  - 「不」字变调规则比较简单：
    * 当「不」字后面的一个字为去声时，变为阳平。 
      不要(`bù yào`) → 不要(`bú yào`)
    *  当「不」字单独使用或在最后一个字的时候，保持原有音调 `bù`
      坚决说不！我绝不答应。要不你先走吧。

- 「上(shǎng)声」变调 Tone Changes for Third Tones
  你好(`nǐ hǎo`) → 你好(`ní hǎo`)

- 「七、八」变调 Tone changes for "七" and "八"
  通常用在口语中，这里不做考虑。例如：「地上一个猴，树上七(qí)个猴」

### 儿化音

https://github.com/zh-lx/pinyin-pro/issues/168

### 轻声

https://github.com/zh-lx/pinyin-pro/issues/177

**Comment by zh-lx** [comment]
汇总至 #246 中统一管理，关闭此 issue
