### ISSUE TITLE
支持叠字符号「々」的注音

### ISSUE THREAD

**Issue by yisibl** [zh-lx/pinyin-pro#201]
## 功能描述

这是一个特殊功能，建议增加一个选项，默认关闭。

々的读音就是读被反复的字的读音，例如，天々(tiān)向上，这里读前面一个字的音。

- https://baike.baidu.com/item/%E3%80%85/9045440
- https://zh.wikipedia.org/wiki/%E5%8F%A0%E5%AD%97%E7%AC%A6%E5%8F%B7

**Comment by koaqiu** [comment]
> “自己动手，丰衣足食。”
> 
> ```js
> var resolveIterationMark = function(string) {
>   var current = string.charAt(0);
>   var result = current;
>   for (var i = 1; i < string.length; ++i) {
>     if (string.charAt(i) !== '々') {
>       current = string.charAt(i);
>     }
>     result += current;
>   }
>   return result;
> };
> ```

```js
const resolveIterationMark = (str) => typeof str  === 'string'  
  ? str.split('々').reduce((s,c, i, a)=> a.length===1?s:`${s}${s.slice(-1)}${c}`) 
  : str;
```

[在线测试](https://play.fe-dev.cn/?entry=index.html&activeFile=main.ts&openConsole=true#eNqVU09r1EAU/yrPUJoENom9STbZIrViwWLBFhQj7jSZ7k5NZmJmduuyBHrxoBaqFy8eVPwDPSjiSaX9NHZbe/Ir+CZZ2y542B6Gmfm993vz3u+9GRqMJ/Sx21VZavhGcOnarYXVuyuLoIFWxAO9Q0p4J4wMyiMDMYCgS0lSnfCcUUUg7pJCUoVOa6vXnSuRAd6EvatU7tBHPdZHlzvO2lVnQWQ5UWw9pegcC64o1/SlxZAmHY1NBuAko2juM7qVi0JNcLZYorphQvsspk51aQDjTDGSOjImKQ3n3MvnIyqmUtpaEAldScmAFoFXI1Vt3mlxwbpIBv84CesDS/A1kucoQ+AhMCacugUyLliuQA1ynWwmkp4ubxyCZTpzMF0vI4y7SprNml+ztNpeJbvRMMYe2JIxa1h1BErYKEQGZs74gHEnL4QOglJIBQWVIu3TJUULFFbwZVI8hBAsqQofF+MdG8JWlZzYAEQAwjAEs7aZADqbeW1wZZ4yZZm/tp+YtlvQpBdTy5KNuAEPGkBsjELclPIOyh6Gc/PSb88MZYnLlSk2wXLmbLzFZduugvo66GmeupDb1ZuY3b1aG41Z/yvAMkcf9jCP0YuXh9+fmbbduBDhz/7O6OOBvn7+dPjj7VT8quop/I5eHRx93T15/+b4+ZfR7repOMdPX59s79eu992M5FbVVhRU7/NtPWatmaG+lPWItX1zNlXN472fv9/tzHZUEzuyKRi3TNNGSSOeiLiX4Udw9Ri6jHNa3FhdvonangndxJGqB8nBN91NKTiO1lCnG40NMjJ8qBCNnc2XhiND/1/pex6VmSu73nmzppQRL43yLwDGhl8=)
