### ISSUE TITLE
读音审查

### ISSUE THREAD

**Issue by yisibl** [zh-lx/pinyin-pro#207]
我对最近的几个读音修正的 commit 做了一些评论，需要统一进一步考证。

https://github.com/zh-lx/pinyin-pro/commit/1e9ecfc18ed132bc77eb1025b5604d01883dad5f
https://github.com/zh-lx/pinyin-pro/commit/3e9d71ec683ab02893b510a77da86ab944570ec7
https://github.com/zh-lx/pinyin-pro/commit/ad0d2f589b29a7afa8c7651af784a6e28fc0a1c3

**Comment by zh-lx** [comment]
英语译词或无标准对照的冷门词汇暂时关闭
