### ISSUE TITLE
希望可以在nonZh的选项中增加一种只去掉标点符号的模式

### ISSUE THREAD

**Issue by huluobotx** [zh-lx/pinyin-pro#211]
## 功能描述

希望可以在nonZh的选项中增加一种只去掉标点符号、保留其它字符（英文单词）的模式

**Comment by zh-lx** [comment]
这个需求过于定制化，暂时不会在库里支持，可以考虑基于现功能自己简单处理下。参考处理代码：https://play.fe-dev.cn/?entry=index.html&activeFile=main.ts&openConsole=true#eNp9U8GOEkEQ/ZWiLwMJM6M3gwPJBtfEk3vYTRRHk96ZgulNT/fY3cAiIVFvRj15M0aNiTeNMR6Fr1FxPfELds8AC5flQvWrelX1XmWmhIkUz4PM5Jy0SFS7dbd7fP/oEBzQiUXk/oFTMWjHBEVMLAYQZUjTMrJxjoZCklGl0diik+Pb/o2YQLiXz4wpfHw8ZCNbcs8/OfC7Mi+oYaccbXEihUHh6HcO25gOHLbfQNAcbXrEcFxIZfY4Y5aarJ3iiCXol48mMMEMo9zXCeXYvh5c2+1omOHY6coUjzidoIrCCim1hVtx0alMJxtOykbAUjuNFoW1IQotsCZsyyKdKFYYMJPCLZvLdOjkrVuw3G0OXhDmlInAaO9mxa9Yzu2wtJ00ybrCnmTNmkLBxIQJmEFfyRy86ukXSro2sbB2aDsZzw20ISbL7y8uvn1dzV8tX87/ffjx6+nz34uPfz4vLDKWiqer+bOYWGJFU6iH3BGrrnXXpmlnOiEt8CjnXhOEFL3MvhwFk6FhI/Rg1qjEBTkt6sxgDu0OTCusFN2HEg6Y7mWN3Yz7KTRDJaAsqEZf5meAXONVDKnYwNqksOA0wXr44NGB36P+k4fhoAmet96s7FWF22X7jBtU231rNRdtkmfSOuCB42+MlRwDLgd172LxZfn609+fb5bv363mb60rlXUNe7PqUr41IjjTUtjblbvH64SOSWujJiaX53NwTNwHolthiDoPdBbuph3FCpiR2X94nj8b
<img width="1070" alt="image" src="https://github.com/zh-lx/pinyin-pro/assets/73059627/658e6ef1-0b25-4e58-84ea-6ed433148be6">
