### ISSUE TITLE
汉字"舍"的所有读音未被全部列出

### ISSUE THREAD

**Issue by mcube-12139** [zh-lx/pinyin-pro#213]
## bug 描述

_使用
```javascript
pinyinPro.pinyin("舍", {
    type: "all",
    toneType: "none",
    multiple: true
})
```
获取汉字"舍"的所有读音时，只获得"she"四声一个读音。
```json
[{"origin":"舍","pinyin":"she","initial":"sh","final":"e","first":"s","finalHead":"","finalBody":"e","finalTail":"","num":4,"isZh":true}]
```
_

## 你预期的样子是？

_获得"she"三声和"she"四声两个读音。_

## pinyin-pro 版本号

_我不知道_

## 引入方式

_浏览器 script 引入_

## 最小成本的复现步骤

- 步骤一 使用浏览器引入`pinyinPro`，然后执行bug描述中的代码。

**Comment by zh-lx** [comment]
需要去掉 `toneType: 'none'` 选项
