### ISSUE TITLE
npm 安装以后，webpack 打包失败

### ISSUE THREAD

**Issue by a1285771357** [zh-lx/pinyin-pro#233]
## 问题描述

_请输入遇到的问题..._

**Comment by zh-lx** [comment]
请提供报错截图或可复现仓库



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月29日 20:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [zh-lx/pinyin-pro] npm 安装以后，webpack 打包失败 (Issue #233) |

问题描述

请输入遇到的问题...

**Comment by a1285771357** [comment]
您好！   邮件已收到。   祝您生活愉快-------------张雷
