### ISSUE TITLE
䌦字的拼音缺失

### ISSUE THREAD

**Issue by xiaofulzm** [zh-lx/pinyin-pro#234]
## 功能描述
䌦解析还是䌦, 而不是拼音
_请输入内容……_
䌦 > dǎo
## 提炼几个功能点

- 功能 1
- 功能 2
- 功能 3

**Comment by zh-lx** [comment]
`pinyin-pro` 内置支持 [《通用汉字规范表》](https://zh.wiktionary.org/wiki/Appendix:%E6%B1%89%E8%AF%AD%E6%8B%BC%E9%9F%B3%E7%B4%A2%E5%BC%95/%E9%80%9A%E7%94%A8%E8%A7%84%E8%8C%83%E6%B1%89%E5%AD%97%E8%A1%A8) 的所有汉字。对于上述非通用汉字规范表中的汉字，已在官方的扩展字符包支持:

```js
import CharsDict from '@pinyin-pro/data/chars.json';
import { addDict } from 'pinyin-pro';

addDict(CharsDict);
```

详见 [@pinyin-pro/data](https://github.com/chinese-data/pinyin-pro-data?tab=readme-ov-file)
