### ISSUE TITLE
诗词中的字体拼音缺失以及拼音

### ISSUE THREAD

**Issue by meetqy** [zh-lx/pinyin-pro#236]
## 功能描述

|字|拼音|参考资料|
|-|-|-|
|㔶|`gòng`|https://baike.baidu.com/item/%E3%94%B6/22750535|
|㶁|`guó`|https://baike.baidu.com/item/%E3%B6%81?fromModule=lemma_search-box|
|䂬|`gǒng`|https://baike.baidu.com/item/%E4%82%AC?fromModule=lemma_search-box|
|䃜|`yī`|https://zh.wiktionary.org/zh-hans/%E4%83%9C|
|䤌|`qiāng`|https://zh.wiktionary.org/wiki/%E4%A4%8C|

**Comment by zh-lx** [comment]
`pinyin-pro` 内置支持 [《通用汉字规范表》](https://zh.wiktionary.org/wiki/Appendix:%E6%B1%89%E8%AF%AD%E6%8B%BC%E9%9F%B3%E7%B4%A2%E5%BC%95/%E9%80%9A%E7%94%A8%E8%A7%84%E8%8C%83%E6%B1%89%E5%AD%97%E8%A1%A8) 的所有汉字。对于上述非通用汉字规范表中的汉字，可以引入官方的扩展字符包支持:

```js
import CharsDict from '@pinyin-pro/data/chars.json';
import { addDict } from 'pinyin-pro';

addDict(CharsDict);
```

详见 [@pinyin-pro/data](https://github.com/chinese-data/pinyin-pro-data?tab=readme-ov-file)
