### ISSUE TITLE
特殊拼音的转换

### ISSUE THREAD

**Issue by tansongchen** [zh-lx/pinyin-pro#241]
## bug 描述

```ts
import { convert } from "pinyin-pro";

for (const pinyin of ["m̄", "hm", "ê̄", "ế", "ê̌", "ề"]) {
  console.log(convert(pinyin, { format: "symbolToNum" }));
}
```

这些都没有转换

## 你预期的样子是？

正确加上声调数字

## pinyin-pro 版本号

3.20.3

## 引入方式

Node.js

## 最小成本的复现步骤

如上

**Comment by zh-lx** [comment]
感谢反馈，目前仅考虑支持大陆标准的汉语拼音，对于非正常拼音符的其他符号不会支持

**Comment by tansongchen** [comment]
@zh-lx  这些本来就是正常的汉语拼音，虽然不是所有字典都会收录这些音，但是至少有一些大陆标准的字典收录了这些音

`hm`，是「噷」的拼音

<img width="673" alt="image" src="https://github.com/zh-lx/pinyin-pro/assets/31927845/38eb4a82-bd0c-490b-968e-6e12a415aa25">

`ê̄, ế, ê̌, ề`，是「诶」「欸」的拼音，[Wikitionary 通用规范汉字字典](https://zh.wiktionary.org/wiki/Appendix:通用规范汉字表)有收录，严格来说这些比拼成 `ei` 更规范

<img width="631" alt="image" src="https://github.com/zh-lx/pinyin-pro/assets/31927845/81e29c35-0ded-41d1-b475-5b701567c9bf">


`m̄` 是鼻音韵母 m 的一声，「嘸」有这个音，而且现在二声 `ḿ` 和四声 `m̀` 都是支持的，一声和三声也可以统一支持

**Comment by zh-lx** [comment]
@tansongchen 还真是，是我孤陋寡闻了。感谢补充，我近期支持一下~
