### ISSUE TITLE
当进行 “三九二”  转化的时候 获取首字母 获取到的数组不对。

### ISSUE THREAD

**Issue by lhc456** [zh-lx/pinyin-pro#26]
## bug 描述

  使用当前的方法时 let nameList = pinyin("三九二",{ pattern: 'initial', type: 'array' }); 输出的为  [ 's', 'j', '' ]，当前的首字母不对   

## 你预期的样子是？

  [ 's', 'j', 'e' ]

## pinyin-pro 版本号

  @3.3.1

## 引入方式
    const { pinyin } = require('pinyin-pro');
     let nameList = pinyin("三九二",{ pattern: 'initial', type: 'array' }); 
_浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
-   const { pinyin } = require('pinyin-pro');
- 步骤二
-  let nameList = pinyin("三九二",{ pattern: 'initial', type: 'array' }); 
- 步骤三

**Comment by lhc456** [comment]
谢谢解惑

**Comment by zh-lx** [comment]
> 谢谢解惑，发现这样获取到的时这样的 [ 's', 'j', 'è' ] 此时的e不应该添加声调的，这个可以通过配置去掉吗？

可以的，加上`toneType: 'none'` 选项：
pinyin("三九二",{ pattern: 'first', type: 'array', toneType: 'none' })

**Comment by lhc456** [comment]
谢谢解答
