### ISSUE TITLE
jie能匹配到'家'有点奇怪

### ISSUE THREAD

**Issue by chenwoniu** [zh-lx/pinyin-pro#263]
## 问题描述

我的项目里'家'非常多，jie都能匹配到，这个字应该不是多音字啊

**Comment by zh-lx** [comment]
家 是有 jie 这个拼音的。见新华字典 235 页

<img width="290" alt="image" src="https://github.com/user-attachments/assets/94c612f9-c743-484e-afbc-e89cafda44d7">
