### ISSUE TITLE
html api ：建议传入的自定义 class 为 false 或 null 或空字符串的时候，不添加 class 属性

### ISSUE THREAD

**Issue by recrute** [zh-lx/pinyin-pro#269]
## 功能描述

html api ：建议传入的自定义 class 为 false 或 null 或空字符串的时候，不添加 class 属性

  resultClass?: string;
  pinyinClass?: string;
  chineseClass?: string;
  nonChineseClass?: string;

建议上述这几个参数，如果用户传入了 false 或 null 或空字符串的时候，不设置 class 属性，

现在版本会出现 class=false, class=null, class=""

**Comment by zh-lx** [comment]
resolved in #271

**Comment by zh-lx** [comment]
已在 `3.25.0` 版本中支持
