### ISSUE TITLE
是否可以添加一个「姓氏」配置项

### ISSUE THREAD

**Issue by tsui66** [zh-lx/pinyin-pro#27]
## 功能描述
因为「姓氏」汉子存在多音字，如下：
```javascript
const pinyin = require('pinyin-pro');
pinyin.pinyin('曾', { multiple: true, type: 'array' });
[ 'céng', 'zēng' ]
```
是否可提供一个功能，如下：
```javascript
const pinyin = require('pinyin-pro');
pinyin.pinyin('曾', { multiple: true, type: 'array', kind: 'lastname' });
[ 'zēng' ]
```
## 提炼几个功能点

- 支持返回姓氏拼音

**Comment by zh-lx** [comment]
> ## 功能描述
> 应为「姓氏」汉子存在多音字，如下：
> 
> ```js
> const pinyin = require('pinyin-pro');
> pinyin.pinyin('曾', { multiple: true, type: 'array' });
> [ 'céng', 'zēng' ]
> ```
> 
> 是否可提供一个功能，如下：
> 
> ```js
> const pinyin = require('pinyin-pro');
> pinyin.pinyin('曾', { multiple: true, type: 'array', kind: 'lastname' });
> [ 'zēng' ]
> ```
> 
> ## 提炼几个功能点
> * 支持返回姓氏拼音

好的，本周会支持一下

**Comment by zh-lx** [comment]
> ## 功能描述
> 因为「姓氏」汉子存在多音字，如下：
> 
> ```js
> const pinyin = require('pinyin-pro');
> pinyin.pinyin('曾', { multiple: true, type: 'array' });
> [ 'céng', 'zēng' ]
> ```
> 
> 是否可提供一个功能，如下：
> 
> ```js
> const pinyin = require('pinyin-pro');
> pinyin.pinyin('曾', { multiple: true, type: 'array', kind: 'lastname' });
> [ 'zēng' ]
> ```
> 
> ## 提炼几个功能点
> * 支持返回姓氏拼音

已增加姓氏模式的支持，可以安装3.4.0版本，传入 `mode: 'surname'` 配置项启用
