### ISSUE TITLE
这个在用html函数，打印在body中的拼音没有多音字识别

### ISSUE THREAD

**Issue by aklws** [zh-lx/pinyin-pro#274]
这个在用html函数，打印在body中的拼音没有多音字识别
比如这样：
![image](https://github.com/user-attachments/assets/66408006-e9af-417a-8bff-d33f8ff4e350)

我wǒ不bù抽chōu雪xuě茄qié，我wǒ吃chī番fān茄qié。

**Comment by zh-lx** [comment]
雪茄这个词语在内置的词典中没有，想要获得更准确的识别率，请使用 `addDict` api 引入官方提供的词典，参考：[addDict](https://pinyin-pro.cn/use/addDict.html)
