### ISSUE TITLE
多音字还是有些错误，比如为人，雪茄等

### ISSUE THREAD

**Issue by Hdurian-CH** [zh-lx/pinyin-pro#277]

**Comment by zh-lx** [comment]
为获取更高的准确率，例如雪茄等常用词，可以通过 `addDict` api 去引入官方完整词典，参考：[addDict](https://pinyin-pro.cn/use/addDict.html)

对于 `为人` 这种词语，因为在 `为人民`、`为人父` 等不同场景下发音不同，纯 js 很难识别，暂不考虑支持，如有需要也可以通过 `addDict` api 添加自定义的拼音
