### ISSUE TITLE
怎么保留字符串中的：换行/空格，文档中没找到

### ISSUE THREAD

**Issue by gcqweb** [zh-lx/pinyin-pro#280]
## 功能描述
_保留字符串中的：换行/空格，文档中没找到_

**Comment by zh-lx** [comment]
默认就是保留的，不符合你的预期吗？可以辛苦给个示例我好解答下：
- 你的输入
- 现在的输出
- 你期望的输出

**Comment by zh-lx** [comment]
无法提供详细信息，暂时关闭此 issue
