### ISSUE TITLE
调拨，结果出来是tiao bo，实际应是diao bo

### ISSUE THREAD

**Issue by bloom8848** [zh-lx/pinyin-pro#281]
## bug 描述
调拨，结果出来是tiao bo，实际应是diao bo
_请输入内容……_

## 你预期的样子是？

_请输入内容……_

## pinyin-pro 版本号

_请输入内容……_

## 引入方式

_浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by zh-lx** [comment]
对于非高频词，如果想要保证准确率，请使用官方提供的完整词典，参考 [使用完整词典](https://pinyin-pro.cn/use/addDict.html#%E4%BD%BF%E7%94%A8%E5%AE%8C%E6%95%B4%E8%AF%8D%E5%85%B8)

[代码示例](https://play.fe-dev.cn/?entry=index.html&activeFile=main.ts&openConsole=true#eNp1Uj1v1EAU/CvLNk4k2wsdOuwIdAkSFSkSCSQ3G+/jvGi/8L67cDpdRYmo6BCioKKgoAf+zkHHX2DX3uTulKTyet7M+M14V1QaAW/LDrWiE1rdO34+PXt5ekIicNSYKj6J4mZWNxRMQwNGSNUBF8MpnDUgJ23Hew8YSOdnT4uHDSVsb94hugLezOUiUF4U50+KqdWOo7xQEMitNQgmyp+d1CBmEds3MFxDGC8kXDrb457mUgrsagEL2UIxvOREGomSq8K3XEH9oLy/64gSFRxNrYBTxZfQV2xEhmzsOlx1YcXySiPkgkgRvsadCzVULABJcE2rfNtLhwSXLi6rrZjHeMlC6rg5yUqmuTQl+uzRqB9VsW021E5zmhjhlyTVijhpltLkhAtxLFska/Kqt5pkI1643ka/RI/tKkAYmCPv8ZbIBEfO2sSJssYk24Nd5eEwCUV7JD34uUJSpz0Osr8/3m3ef8u2HKugVHYWJr+/bz58/fPz4+bL53+/PmV5Eh+GYON+heaufO2tCQFXsYQmDXxDJ2RAIrbdOMINjbfITxgDr0vfsd1xfqW5M+atFjfYQnrckUTXdWPWdP0fuwUYOA==)

<img width="1619" alt="image" src="https://github.com/user-attachments/assets/fb5ba9ba-6a0c-46da-867b-9b5fcdcf5aa3">
