### ISSUE TITLE
当获取拼音首字母时 同时获取音调num时，只会出现首字母

### ISSUE THREAD

**Issue by weiailmy** [zh-lx/pinyin-pro#29]
## bug 描述

当获取拼音首字母时 同时获取音调num时，只会出现首字母

## 你预期的样子是？

首字母并携带音调num

## pinyin-pro 版本号

最新版

## 引入方式

node require 引入

## 最小成本的复现步骤

pinyin.pinyin('山西',{pattern:'first',toneType:'num'})
pinyin.pinyin('陕西',{pattern:'first',toneType:'num'})
- 步骤一
- 步骤二
- 步骤三

**Comment by zh-lx** [comment]
感谢反馈，晚上会进行修复

> ## bug 描述
> 当获取拼音首字母时 同时获取音调num时，只会出现首字母
> 
> ## 你预期的样子是？
> 首字母并携带音调num
> 
> ## pinyin-pro 版本号
> 最新版
> 
> ## 引入方式
> node require 引入
> 
> ## 最小成本的复现步骤
> pinyin.pinyin('山西',{pattern:'first',toneType:'num'}) pinyin.pinyin('陕西',{pattern:'first',toneType:'num'})
> 
> * 步骤一
> * 步骤二
> * 步骤三

感谢反馈，晚上会修复

**Comment by zh-lx** [comment]
已修复，请安装 `3.4.1` 版本体验
