### ISSUE TITLE
对多音字的处理

### ISSUE THREAD

**Issue by lixingyangok** [zh-lx/pinyin-pro#31]
感谢作者的贡献 🌹🌹🌹🌹

pinyin('李乐', { toneType: 'none' }); // 'li le'

● 希望也能得到其它形式的拼音 // 如把通过“李乐”得到 'li le' 和 'li yue' 这样的多种可能性
● 因为我遇到的工程有一个输入拼音首字母来快速检索的功能，之前用手段经常不能匹配到“会计”功能，因为程序以为那个是 hui ji

**Comment by zh-lx** [comment]
感谢支持
词句的情况下，如果词汇或句子过长，多音字的排列组合的结果可能非常多，这种情况可能比较难以处理。
对于拼音识别不准确的情况下，可以考虑使用 `customPinyin` api 去自定义自己的拼音。
然后元旦我会新增一个专门用于拼音匹配的 api，会识别每个字的多音字情况，可以更方便的支持你需要的这种功能。

**Comment by zh-lx** [comment]
已新增了 `match` api 对拼音文本匹配功能进行了支持，可以下载最新的 3.5.0 版本进行使用，具体使用方法可以 Readme 文档

**Comment by npuichigo** [comment]
加个crf之类的模型处理多音字？

**Comment by zh-lx** [comment]
> 加个crf之类的模型处理多音字？

纯前端的包，加crf训练后包体积太大了😂
