### ISSUE TITLE
可以增加 过滤数字等除了字母的功能么

### ISSUE THREAD

**Issue by chenning111** [zh-lx/pinyin-pro#33]
## 功能描述

_请输入内容……_

## 提炼几个功能点

 pinyin('汉语2拼音11', {pattern: 'first', toneType: 'none'});  // 期望: h y p y 去除  11 2

**Comment by zh-lx** [comment]
好的，本周会增加一个配置项支持一下

**Comment by chenning111** [comment]
感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zh-lx/pinyin-pro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月4日(星期二) 上午10:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zh-lx/pinyin-pro] 可以增加 过滤数字等除了字母的功能么 (Issue #33)





 
好的，本周会增加一个配置项支持一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zh-lx** [comment]
已新增 `removeNonZh` 可选项，设置为 `true` 时可过滤掉输入字符串中的非汉字字符
