### ISSUE TITLE
新增属性removeNonZh 导致内存溢出

### ISSUE THREAD

**Issue by chenning111** [zh-lx/pinyin-pro#35]
## bug 描述
当传值为 全特殊字符 ，不包含中文时 提示Maximum call stack size exceeded 例如 aaa
_请输入内容……_

## 你预期的样子是？
_请输入内容……_

## pinyin-pro 版本号
3.6.0
_请输入内容……_

## 引入方式

_浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_

## 最小成本的复现步骤

（请告诉我们，如何最快的复现该 bug）

- 步骤一
- 步骤二
- 步骤三

**Comment by zh-lx** [comment]
> ## bug 描述
> 当传值为 全特殊字符 ，不包含中文时 提示Maximum call stack size exceeded 例如 aaa _请输入内容……_
> 
> ## 你预期的样子是？
> _请输入内容……_
> 
> ## pinyin-pro 版本号
> 3.6.0 _请输入内容……_
> 
> ## 引入方式
> _浏览器 script 引入 / esmodule(浏览器 import 引入) / commonjs(node require 引入)_
> 
> ## 最小成本的复现步骤
> （请告诉我们，如何最快的复现该 bug）
> 
> * 步骤一
> * 步骤二
> * 步骤三

感谢反馈，3.6.1已修复该问题
