### ISSUE TITLE
Add bundled ESM dist file

### ISSUE THREAD

**Issue by ryanlin1986** [zh-lx/pinyin-pro#39]
## 功能描述

希望增加打包后的ESM文件，
有些环境下没有办法用webpack之类的打包工具， 也不能用requirejs，只希望直接用ESM动态导入使用，如：
```js
import('/lib/pinyin-pro.js').then(exports=>{
      let pinyin=exports.pinyin('测试');
});
```

**Comment by zh-lx** [comment]
已增加 esm 模式的打包，可以通过如下方式引入看能否解决问题：
```js
import('pinyin-pro').then((exports) => {
  exports.pinyin('汉语拼音'); // 'hàn yǔ pīn yīn'
});
```

**Comment by ryanlin1986** [comment]
神速！ 非常感谢， 完美解决需求!

**Comment by zh-lx** [comment]
客气啦😉有空就会第一时间支持大家的需求的



---- 回复的原邮件 ----
| 发件人 | ryan ***@***.***> |
| 日期 | 2022年01月09日 00:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zh-lx/pinyin-pro] Add bundled ESM dist file (Issue #39) |

神速！ 非常感谢， 完美解决需求!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
