### ISSUE TITLE
Wrong pinyin for an idiom

### ISSUE THREAD

**Issue by cheeaun** [zh-lx/pinyin-pro#43]
## bug 描述

`pinyin('价廉物美')` returns `jià lián wù měi` which is correct.

But, `pinyin('物美价廉')` also return `jià lián wù měi` which is incorrect (wrongly ordered).

## 你预期的样子是？

`pinyin('物美价廉')` should return `wù měi jià lián`.

## pinyin-pro 版本号

v3.7.1

## 引入方式

Tested both in browser and node environment. For browser, ViteJS is used.

## 最小成本的复现步骤

```
var {pinyin} = require("pinyin-pro")
console.log(pinyin('物美价廉') + ' -- ' + pinyin('价廉物美'))
```

Here's a RunKit: https://runkit.com/cheeaun/6205478538a7f900084c18ca

Here's a screenshot:
<img width="447" alt="Screenshot 2022-02-11 at 1 20 06 AM" src="https://user-images.githubusercontent.com/2296/153461503-fe4fcf59-adcf-4fee-b6b9-9c66c1427ce5.png">

Notes: I'm not sure if this affect other idioms too. I found that this idiom is inside `main/data/dict3.ts`, and the library seems to only check if characters exists without looking at the indices?

**Comment by cheeaun** [comment]
Thanks! I've tested with the latest version and confirmed that it's fixed! 🙇‍♂️

**Comment by zh-lx** [comment]
> Thanks! I've tested with the latest version and confirmed that it's fixed! 🙇‍♂️

Thanks!
