### ISSUE TITLE
Unicode 扩展汉字解析 bug

### ISSUE THREAD

**Issue by ydfzgyj** [zh-lx/pinyin-pro#45]
## bug 描述

String.split 无法将多字节的 Unicode 扩展汉字正常转换到数组，而是按照两个字符处理，导致返回两个乱码

## 你预期的样子是？

像正常情况下匹配不到拼音时一样，返回原字符

## pinyin-pro 版本号

v3.7.2

## 引入方式

不影响

## 最小成本的复现步骤

```
pinyinPro.pinyin('龥') // 字库中没有的双字节字符\u9fa5，返回"龥"
pinyinPro.pinyin('𧒽') // 字库中没有的四字节字符\ud85d\udcbd，返回"� �"
```

**Comment by ydfzgyj** [comment]
当前问题并没有完全修复，包含扩展字符的字符串最后会少掉一截
复现：
```javascript
pinyinPro.pinyin('𧒽测试')  // 输出 "� � cè"，因为“𧒽”占两个字符，因此试的拼音不见了
```

**Comment by zh-lx** [comment]
> 当前问题并没有完全修复，包含扩展字符的字符串最后会少掉一截 复现：
> 
> ```js
> pinyinPro.pinyin('𧒽测试')  // 输出 "� � cè"，因为“𧒽”的长度为2，因此试的拼音不见了
> ```

感谢反馈，这次在 #50 彻底修复了！请使用 `3.8.2` 版本再验证下
