### ISSUE TITLE
如果是英文，则转换出来的字符串虽然也是英文，但是会字母间会出现空格

### ISSUE THREAD

**Issue by duanxingyu** [zh-lx/pinyin-pro#46]
## 如果是英文，则转换出来的字符串虽然也是英文，但是会字母间会出现空格

_应用场景：可以输入汉字或者英文，但是如果是汉字的话，需要转成拼音，中间用“_”来连接，若是英文的话，就保持原样。如： 输入“负责人”，则转换成“fu_ze_ren”，若是输入的“changeBy”,输入应该还是“changeBy”，但是转换出来的结果却是c h a r g e B y，中间自动加了空格，前端做正则需要将空格替换成"_"，结果就成“c_h_a_r_g_e_B_y”，所以可以适配下英文状态下的转换规则么？，_

**Comment by duanxingyu** [comment]
3.3.1及以下版本是正常的，从3.4版本就变成上面那个样子了

**Comment by zh-lx** [comment]
> 3.3.1及以下版本是正常的，从3.4版本就变成上面那个样子了

您好，感谢反馈。已增加一个新的参数 `nonZh`，传输 `nonZh: 'consecutive'` 即可使非汉字字符输出紧凑。例如：
```js
pinyin('我very喜欢你', { nonZh: 'consecutive' }); // 'wǒ very xǐ huān nǐ'
```
