### ISSUE TITLE
能否增加对古诗词的支持？

### ISSUE THREAD

**Issue by KERWINWANG510** [zh-lx/pinyin-pro#53]
## 功能描述
希望增加对古诗词拼音的支持
_请输入内容……_
比如古诗鹿柴读音是lu zhai，而不是lu chai

**Comment by zh-lx** [comment]
感谢留言，古诗的范围太广太大了，目前做不到涵盖古诗内容，建议使用这个包去做到古诗中大部分汉字的拼音转换，对于个别诗句的转换误差问题可以通过 [customPinyin](https://github.com/zh-lx/pinyin-pro#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8B%BC%E9%9F%B3) 方法来手动纠正一下。
