### ISSUE TITLE
关于韵母`ü`

### ISSUE THREAD

**Issue by XavierCHN** [zh-lx/pinyin-pro#54]
目前的版本是否有考虑将韵母`ü`修改为`v`的选项支持？甚至默认将`ü`修改为`v`？因为`ü`在很多环境下使用会有问题
例如
```
pinyin('吕布', { toneType: 'none' }) // 'lü bu'
```
当然，这个问题显然可以通过字符串替换来达成。
如果有支持当然就更好了。

**Comment by mango-csl** [comment]
今天也碰到了 同样的问题 /dog/

**Comment by zh-lx** [comment]
已在 `3.9.0` 版本中增加了  `v: true` 可选项将拼音 `ü` 替换为 `v`，可以参照 [示例](https://github.com/zh-lx/pinyin-pro#%E5%B0%86%E6%8B%BC%E9%9F%B3-%C7%9A-%E6%9B%BF%E6%8D%A2%E4%B8%BA-v)

**Comment by mango-csl** [comment]
你好，你的来件已收到。
