### ISSUE TITLE
建议增强match方法的功能

### ISSUE THREAD

**Issue by JackieCheung** [zh-lx/pinyin-pro#56]
## 功能描述
建议增强match方法的功能

## 提炼几个功能点

1.增加一个配置项，允许设置不分词匹配，如：match('汉语拼音', 'hanpin')在不分词匹配的情况下应该返回null；

2.增加对中文的匹配，如：match('汉语拼音', '语拼')应该返回[1, 2]，虽然可以自己通过字符串匹配来实现，但是还是希望match方法可以兼容

**Comment by zh-lx** [comment]
思考了一下，这两个功能是否要支持待讨论：
第一个功能点：不分词匹配的情况下，只需要使用`pinyin('汉语拼音').startsWith('hanpin')`就可以实现，加一个match的增强方法感觉使用上也并没有简便太多
第二个功能点属于一个纯汉字字符串的匹配，跟“pinyin”的概念没有太大的关联。

**Comment by JackieCheung** [comment]
> 思考了一下，这两个功能是否要支持待讨论： 第一个功能点：不分词匹配的情况下，只需要使用`pinyin('汉语拼音').startsWith('hanpin')`就可以实现，加一个match的增强方法感觉使用上也并没有简便太多 第二个功能点属于一个纯汉字字符串的匹配，跟“pinyin”的概念没有太大的关联。

第一个功能点：如果是查询“语音”呢，主要的使用场景是：通过获取匹配到的下标（不分词匹配返回`[开始下标，结束下标]`），用来高亮显示所对应的关键字。
第二个功能点：的确可以自己处理，主要的使用场景是：下拉选择器需要同时支持中文/拼音/拼音首字母的筛选，如果能统一在match方法里面处理，就方便了

**Comment by zh-lx** [comment]
> > 思考了一下，这两个功能是否要支持待讨论： 第一个功能点：不分词匹配的情况下，只需要使用`pinyin('汉语拼音').startsWith('hanpin')`就可以实现，加一个match的增强方法感觉使用上也并没有简便太多 第二个功能点属于一个纯汉字字符串的匹配，跟“pinyin”的概念没有太大的关联。
> 
> 第一个功能点：如果是查询“语音”呢，主要的使用场景是：通过获取匹配到的下标（不分词匹配返回`[开始下标，结束下标]`），用来高亮显示所对应的关键字。 第二个功能点：的确可以自己处理，主要的使用场景是：下拉选择器需要同时支持中文/拼音/拼音首字母的筛选，如果能统一在match方法里面处理，就方便了

理解使用场景了，近期会考虑支持一下

**Comment by zh-lx** [comment]
第二点已在 #70 中支持
第一点可以自己对结果识别是否为连续输出实现

**Comment by xmflswood** [comment]
@JackieCheung 
第一点可以用这个库解决 https://github.com/xmflswood/pinyin-match/
@zh-lx 
也可以考虑match方法参考这个库的解决方案

pinyin-pro 很棒❤
