### ISSUE TITLE
姓名拉丁化首字母大写

### ISSUE THREAD

**Issue by iyoua** [zh-lx/pinyin-pro#60]
## 功能描述

有三个文本框，第一个输入姓氏，第个输入名字，第三个框自动输出拉丁化的姓名拼音，如姓氏：刘，名字：德华，输出：Liu Dehua

这个效果怎么实现呢？

**Comment by zh-lx** [comment]
代码如下：
```js
import { pinyin } from 'pinyin-pro';

const firstName = '刘';
const lastName = '德华';

const pinyinOfFirstName = pinyin(firstName, {
  mode: 'surname',
  toneType: 'none',
});

const pinyinOfLastName = pinyin(lastName, {
  toneType: 'none',
  type: 'array',
}).join('');

const result = `${
  (pinyinOfFirstName[0] || '').toUpperCase() + pinyinOfFirstName.substr(1)
} ${(pinyinOfLastName[0] || '').toUpperCase() + pinyinOfLastName.substr(1)}`;
```
另外给你写了一个在线示例，可以看：https://codesandbox.io/s/elated-dirac-3rpcow?file=/src/App.js

**Comment by iyoua** [comment]
非常感谢！我得弄个网页来测试一下，您发的那个在线示例我这里打开很慢，搞不懂咋调试。

**Comment by zh-lx** [comment]
> 非常感谢！我得弄个网页来测试一下，您发的那个在线示例我这里打开很慢，搞不懂咋调试。 我对JS不熟悉，能否帮我写个HTML网页呢，我刚才怎么弄都不成功。网页功能就如以上描述的那样，只要姓氏和名字两个文本框有汉字输入，第三个文本框就动态地显示拼音化的姓名。再次感谢大神！

react版本的代码如下：
```js
import { useState } from "react";
import { pinyin } from "pinyin-pro";
import "./styles.css";

export default function App() {
  const [firstName, setFirstName] = useState("刘");
  const [lastName, setLastName] = useState("德华");
  const getPinyin = () => {
    const pinyinOfFirstName = pinyin(firstName, {
      mode: "surname",
      toneType: "none"
    });

    const pinyinOfLastName = pinyin(lastName, {
      toneType: "none",
      type: "array"
    }).join("");

    const result = `${
      (pinyinOfFirstName[0] || "").toUpperCase() + pinyinOfFirstName.substr(1)
    } ${
      (pinyinOfLastName[0] || "").toUpperCase() + pinyinOfLastName.substr(1)
    }`;

    return result;
  };
  return (
    <div className="App">
      <div>
        姓：
        <input
          type="text"
          value={firstName}
          onChange={(e) => setFirstName(e.target.value)}
        />
      </div>
      <div>
        名：
        <input
          type="text"
          value={lastName}
          onChange={(e) => setLastName(e.target.value)}
        />
      </div>
      <div>
        拼音：
        <input type="text" value={getPinyin()} />
      </div>
    </div>
  );
}
```

**Comment by iyoua** [comment]
谢谢您了，这个对您来说可能很简单的，但对我来说很不容易。终于调试成功了，代码如下：
`<!DOCTYPE html>
<html　 xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta　http-equiv="Content-Type"　content="text/html;　 charset=utf-8"　/>
<title>汉字姓名转拼音</title>
<script src="https://cdn.jsdelivr.net/gh/zh-lx/pinyin-pro@latest/dist/pinyin-pro.js"></script>
</head>
<body>

<script>

var { pinyin } = pinyinPro;

function fullName(){
  var firstName = document.getElementById("firstName").value;
  var lastName = document.getElementById("lastName").value;

  var pinyinOfFirstName = pinyin(firstName, {
      mode: 'surname',
      toneType: 'none',
    });

  var pinyinOfLastName = pinyin(lastName, {
      toneType: 'none',
      type: 'array',
    }).join('');

  var result = `${
      (pinyinOfFirstName[0] || '').toUpperCase() + pinyinOfFirstName.substr(1)} ${(pinyinOfLastName[0] || '').toUpperCase() + pinyinOfLastName.substr(1)}`;
   
   document.getElementById("pinyinName").value = result;
}

</script>

<div id="text">
<label>姓    氏：</label><input type="text" onchange="fullName()" id="firstName"><br>
<label>名    字：</label><input type="text" onchange="fullName()" id="lastName"><br>
<label>拼音名：</label><input type="text" id="pinyinName"><br>
</div>

</body>
</html>`
但有个BUG，复姓的效果就不对了，如：欧阳奋强，它的结果是：Ou yang Fenqiang
理想的结果是：Ouyang Fenqiang

**Comment by iyoua** [comment]
问题已解决，用.replace(/\s/g,"")去掉姓氏字符串中的空格。谢谢作者老师！

**Comment by zh-lx** [comment]
> 问题已解决，用.replace(/\s/g,"")去掉姓氏字符串中的空格。谢谢作者老师！

客气客气
