### ISSUE TITLE
cdn失效,建议更换

### ISSUE THREAD

**Issue by biusp** [zh-lx/pinyin-pro#62]
## 问题描述

_请输入遇到的问题..._

**Comment by zh-lx** [comment]
感谢反馈，现在使用的是 jsdelivr 的 cdn 托管，今天可能因为他们的服务故障导致无法访问，现在已恢复。
过两天会自己购买一个 cdn 然后上传以保证稳定性。
<b>如果你自己或者公司项目有 cdn 的话，最推荐的做法时将 js 文件下载下来上传到公司的 cdn， 以保证服务的稳定性。</b>

**Comment by Cjiangha** [comment]
同问，下不下来 js文件去哪下呢？

**Comment by Cjiangha** [comment]
同问，下不下来，具体是去哪下呢？dist下的？

**Comment by biusp** [comment]
> 同问，下不下来，具体是去哪下呢？dist下的？

对

**Comment by zh-lx** [comment]
> 同问，下不下来，具体是去哪下呢？dist下的？

是的，是这个文件 `/dist/pinyin-pro.js`
