### ISSUE TITLE
对于多音词处理的问题

### ISSUE THREAD

**Issue by PrinOrange** [zh-lx/pinyin-pro#65]
感谢项目贡献者的工作！我认为可以对本项目的一些功能做出改进：
本项目对于多音词处理上有一些小bug.而且根据文档，`multiple`属性不能解决此问题
例如
```javascript
pinyin("朝阳");
//输出"zhāo cháo yáng"
```
其中“朝”字被自动检测出两种读音。
如果关闭`multiple`属性为false，输出结果**仍然是**`zhāo cháo yáng`，一行出现了三个拼音。
"朝阳"一词有两种正确读音：zhao yang和chao yang均正确。对于其他多音词也可能会出现这个问题。
我认为可以把多音词的各种读音都返回到一个数组中。

第二个问题就是，项目中的多音词库似乎不足。比如“增长”，有`zeng zhang`和`zeng chang`两种读音。程序只能得到`zeng zhang`读音。再比如"大夫"，有`da fu`(古代官职名)和`dai fu`(医生称谓)，项目中只能返回dai fu一词。
我认为可以在现有的权威拼音数据库中更新一些数据，可以解决这个问题。

**Comment by PrinOrange** [comment]
找到了一些数据项目，可以作为参考：
汉语词汇拼音数据：https://github.com/mozillazg/phrase-pinyin-data
汉字拼音数据：https://github.com/mozillazg/pinyin-data

**Comment by zh-lx** [comment]
感谢您的反馈，朝阳这个词是因为目前我的词库里拼音有误，这两天会修改一下。

**Comment by duanxingyu** [comment]
负责人，会被转换成fu_zhai_ren，正确的是fu_ze_ren，也是多音词的问题

**Comment by zh-lx** [comment]
好的，感谢反馈



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月27日 11:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zh-lx/pinyin-pro] 对于多音词处理的问题 (Issue #65) |

负责人，会被转换成fu_zhai_ren，正确的是fu_ze_ren，也是多音词的问题
