### ISSUE TITLE
增加分别获取介音和韵尾的功能

### ISSUE THREAD

**Issue by CrSjimo** [zh-lx/pinyin-pro#74]
例如，如果使用pattern: final模式获取”状“字的拼音，得到的结果是”uang“，由介音”u“和韵尾”ang“构成。希望能够增加一个新功能，可以将韵母的这两部分分离。

**Comment by zh-lx** [comment]
可以的，本周会考虑加入该功能



---- 回复的原邮件 ----
| 发件人 | Crindzebra ***@***.***> |
| 日期 | 2022年10月29日 17:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [zh-lx/pinyin-pro] 增加分别获取介音和韵尾的功能 (Issue #74) |

例如，如果使用pattern: final模式获取”状“字的拼音，得到的结果是”uang“，由介音”u“和韵尾”ang“构成。希望能够增加一个新功能，可以将韵母的这两部分分离。

**Comment by zh-lx** [comment]
已在 3.12.0 版本中支持该功能，可参照 [v3.12.0](https://pinyin-pro.cn/use/pinyin.html#%E9%9F%B5%E5%A4%B4-%E4%BB%8B%E9%9F%B3-%E9%9F%B5%E8%85%B9-%E9%9F%B5%E5%B0%BE)
