### ISSUE TITLE
关于韵母”ü“

### ISSUE THREAD

**Issue by CrSjimo** [zh-lx/pinyin-pro#75]
使用pattern: final模式获取类似“序”（xu），“局”（ju），“与”（yu）等字的韵母时，得到的结果是“u”。

然而这些字事实上的韵母应该是是“ü”。

**Comment by zh-lx** [comment]
这里的韵母是按照它们在拼音中的来显示的，虽然发音是按照 `ü` 来的，但是在拼音中 j、q、x 后面的 `ü` 应省略两点显示 `u`。
不过按照你的说法单独取出韵母来确实好像显示 `ü` 更合理一些，这里我考虑在 pattern 字段中多加一个 `strictFinal` 可选项来将他们显示为 `ü`，这周末会支持这个功能

**Comment by zh-lx** [comment]
已在 3.12.0 修复该问题
