### ISSUE TITLE
部分包含儿化音的字符串在转换时可能报错

### ISSUE THREAD

**Issue by Huanian97** [zh-lx/pinyin-pro#87]
## bug 描述

包含下列儿化音短句的字符串，如果短句后有任意字符(包括空格/换行)，在转换时一定会报错
( `mode: "surname"` 时 `那阵儿`、`那会儿` 因为包含姓氏不报错)

- 有点儿
- 压根儿
- 那会儿
- 自个儿
- 好好儿
- 挨个儿
- 那阵儿
- 大婶儿
- 个头儿
- 一丁点儿

## pinyin-pro 版本号

`"pinyin-pro": "^3.13.0"`

## 引入方式

commonjs(node require 引入)

## 最小成本的复现步骤

> https://pinyin-pro.cn/run/run.html

**Comment by zh-lx** [comment]
感谢反馈！我排查一下

**Comment by zh-lx** [comment]
已修复该问题，请安装 `3.13.1` 版本体验
