### ISSUE TITLE
Cannot convert string of "一丁点儿\n" to Pinyin.

### ISSUE THREAD

**Issue by jaehyun-hwangf** [zh-lx/pinyin-pro#90]
## bug
Can not convert the string of "一丁点儿\n" to Pinyin.
I would appreciate it if you could tell me the cause or solve it. 🙂

### script
```javascript
const { pinyin } = require('pinyin-pro')

const res = pinyin("一丁点儿\n")
```

### error result
```
TypeError: Cannot read properties of undefined (reading 'result')
    at {workspace}/node_modules/pinyin-pro/dist/index.js:1:286390
    at E ({workspace}/node_modules/pinyin-pro/dist/index.js:1:286561)
```

**Comment by zh-lx** [comment]
Thank you for feedback on this issue. It is a bug and I will fix it as soon as possible.

**Comment by zh-lx** [comment]
The reason of this problem is that the pinyin of `一丁点儿` in dictionary was error. I have fixed it and welcome to use the latest version `3.13.2`.

**Comment by jaehyun-hwangf** [comment]
Thank you for solving it quickly 👍
