### ISSUE TITLE
Speed benchmark is not comparing apple to apple

### ISSUE THREAD

**Issue by Brooooooklyn** [zh-lx/pinyin-pro#99]
Since `pinyin-pro` doesn't support `segment` feature, it seems you shouldn't compare `pinyin-pro` with `segment` options enabled in `pinyin` and `@napi-rs/pinyin`.

The results from my computer without `segment` enabled in `pinyin` and `@napi-rs/pinyin`:

### Hardware

```
OS: macOS 12.3.1 21E258 arm64
Host: MacBookPro18,2
Kernel: 21.4.0
Shell: zsh 5.8
CPU: Apple M1 Max
GPU: Apple M1 Max
Memory: 9539MiB / 65536MiB
```

### Result

```
node speed.js
pinyin-pro 转换 5000 字数时间: 3.193ms
pinyin 转换 5000 字数时间: 1.835ms
@napi-rs/pinyin 转换 5000 字数时间: 0.584ms

node speed.js
pinyin-pro 转换 10000 字数时间: 9.691ms
pinyin 转换 10000 字数时间: 5.644ms
@napi-rs/pinyin 转换 10000 字数时间: 1.093ms

node speed.js
pinyin-pro 转换 1000000 字数时间: 313.71ms
pinyin 转换 1000000 字数时间: 185.946ms
@napi-rs/pinyin 转换 1000000 字数时间: 135.24ms
```

This result is matched with benchmark results in [`@napi-rs/pinyin`](https://github.com/Brooooooklyn/pinyin#%E4%B8%8E-pinyin-%E6%80%A7%E8%83%BD%E5%AF%B9%E6%AF%94)

**Comment by zh-lx** [comment]
`pinyin-pro` defaults to having `segment` enabled in all cases(otherwise it wouldn't have such high accuracy). So my current comparison is reasonable.
